# Generated by Django 4.1.7 on 2023-04-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='Name_Surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Surname',
        ),
        migrations.AddField(
            model_name='profile',
            name='Biography',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='emailaddress',
            field=models.CharField(default='email@email.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Password',
            field=models.CharField(default='password', max_length=15),
        ),
    ]
