version: "3.9"

services:
  app:
    build:
      context: .

    command: >
      sh -c "python socialnetworkplatform/manage.py migrate &&
             python socialnetworkplatform/manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    volumes:
      - ./StoriesPlatform:/StoriesPlatform
    environment:
      - DB_HOST= db
      - DB_NAME=DjangoDB
      - DB_USER=DjangoDBuser
      - DB_PASS=112358
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=DjangoDB
      - POSTGRES_USER=DjangoDBuser
      - POSTGRES_PASSWORD=112358