# Generated by Django 4.1.7 on 2023-04-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='author',
            new_name='author_id',
        ),
    ]
