# Generated by Django 4.1.7 on 2023-04-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_author_story_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='author_id',
            new_name='author',
        ),
    ]
