# Generated by Django 4.1.7 on 2023-04-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_story_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='placeID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
